// const mongoose = require("mongoose");
// // const User = require("./models/user");
// const { Color, Palette } = require("./models/color");
// mongoose.connect("mongodb://127.0.0.1:27017/matchminicolor");

// let palettes = [
//     new Palette({
//         name: "Prueba carga datos",
//         idUser: "660959c02ec8cca57874a26a",
//         colors: [
//             {
//                 _id: "661585b2f177980d58c7ce47",
//                 company: "Vallejo",
//                 gama: "Game Color",
//                 name: "Amarillo Dorado",
//                 red: 214,
//                 green: 116,
//                 blue: 25,
//                 code: "72007",
//                 feature: "Acrílica",
//             },
//             {
//                 _id: "661585b2f177980d58c7ce46",
//                 company: "Vallejo",
//                 gama: "Model Color",
//                 name: "Amarillo Lunar",
//                 red: 238,
//                 green: 184,
//                 blue: 0,
//                 code: "70858",
//                 feature: "Acrílica",
//             }]
//     }),
// ];

// let colors = [
        // new Color({
        //     company: "Vallejo",
        //     gama: "Game Color",
        //     name: "Amarillo Lunar",
        //     red: 238,
        //     green: 184,
        //     blue: 0,
        //     code: "72005",
        //     feature: "Acrílica",
        // }),
//         new Color({
//             company: "Vallejo",
//             gama: "Game Color",
//             name: "Amarillo Dorado",
//             red: 214,
//             green: 116,
//             blue: 25,
//             code: "72007",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Hielo",
//             red: 237,
//             green: 208,
//             blue: 114,
//             code: "70858",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Claro",
//             red: 248,
//             green: 211,
//             blue: 70,
//             code: "70949",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Limón",
//             red: 228,
//             green: 210,
//             blue: 2,
//             code: "70952",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Intenso",
//             red: 241,
//             green: 199,
//             blue: 1,
//             code: "70915",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Mate",
//             red: 246,
//             green: 186,
//             blue: 53,
//             code: "70953",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Dorado",
//             red: 248,
//             green: 167,
//             blue: 52,
//             code: "70948",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Verde",
//             red: 222,
//             green: 222,
//             blue: 38,
//             code: "70954",
//             feature: "Acrílica",
//         }),
//         new Color({
//             company: "Vallejo",
//             gama: "Model Color",
//             name: "Amarillo Lasur",
//             red: 206,
//             green: 182,
//             blue: 94,
//             code: "70806",
//             feature: "Acrílica",
//         }),

// ]
// let colors = [
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 1",
//         red: 254,
//         green: 138,
//         blue: 185,
//         code: "00001",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 2",
//         red: 254,
//         green: 138,
//         blue: 186,
//         code: "00002",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 3",
//         red: 255,
//         green: 137,
//         blue: 186,
//         code: "00003",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 4",
//         red: 250,
//         green: 137,
//         blue: 186,
//         code: "00004",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 5",
//         red: 253,
//         green: 137,
//         blue: 184,
//         code: "00005",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 6",
//         red: 254,
//         green: 139,
//         blue: 186,
//         code: "00006",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 7",
//         red: 252,
//         green: 138,
//         blue: 185,
//         code: "00008",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 8",
//         red: 253,
//         green: 140,
//         blue: 185,
//         code: "00009",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 9",
//         red: 249,
//         green: 138,
//         blue: 135,
//         code: "00010",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 10",
//         red: 244,
//         green: 151,
//         blue: 58,
//         code: "00011",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 11",
//         red: 254,
//         green: 129,
//         blue: 192,
//         code: "00012",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 12",
//         red: 255,
//         green: 140,
//         blue: 170,
//         code: "00013",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 13",
//         red: 248,
//         green: 125,
//         blue: 158,
//         code: "00015",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 14",
//         red: 250,
//         green: 120,
//         blue: 180,
//         code: "00016",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 15",
//         red: 240,
//         green: 120,
//         blue: 180,
//         code: "00017",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 16",
//         red: 250,
//         green: 170,
//         blue: 120,
//         code: "00018",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Prueba 17",
//         red: 255,
//         green: 97,
//         blue: 168,
//         code: "00019",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Blanco Calavera",
//         red: 255,
//         green: 255,
//         blue: 255,
//         code: "72001",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Blanco Sucio",
//         red: 254,
//         green: 244,
//         blue: 219,
//         code: "72101",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Amarillo Soleado",
//         red: 254,
//         green: 244,
//         blue: 219,
//         code: "72006",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Amarillo Tóxico",
//         red: 232,
//         green: 212,
//         blue: 87,
//         code: "72109",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Azul Eléctrico",
//         red: 67,
//         green: 153,
//         blue: 178,
//         code: "72023",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Azul Ultramar",
//         red: 55,
//         green: 58,
//         blue: 103,
//         code: "72022",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Gris Lobo",
//         red: 195,
//         green: 209,
//         blue: 209,
//         code: "72047",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Gris Sombra",
//         red: 83,
//         green: 93,
//         blue: 105,
//         code: "72048",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Carne Élfica",
//         red: 234,
//         green: 215,
//         blue: 185,
//         code: "72098",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Carne Rosa",
//         red: 229,
//         green: 138,
//         blue: 107,
//         code: "72100",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Naranja Atardecer",
//         red: 244,
//         green: 151,
//         blue: 58,
//         code: "72110",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Negro",
//         red: 0,
//         green: 0,
//         blue: 0,
//         code: "72101",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Rojo Sanguina",
//         red: 212,
//         green: 28,
//         blue: 26,
//         code: "72010",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Rojo Visceral",
//         red: 125,
//         green: 31,
//         blue: 31,
//         code: "72011",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Verde Escorpena",
//         red: 79,
//         green: 132,
//         blue: 54,
//         code: "72032",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Verde Malicioso",
//         red: 0,
//         green: 162,
//         blue: 125,
//         code: "72025",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Purpura",
//         red: 134,
//         green: 35,
//         blue: 81,
//         code: "72014",
//         feature: "Acrílica",
//     }),
//     new Color({
//         company: "Vallejo",
//         gama: "Game Color",
//         name: "Purpura Alienígena",
//         red: 113,
//         green: 97,
//         blue: 168,
//         code: "72076",
//         feature: "Acrílica",
//     }),
// ];

// let users = [
//     new User({
//         name: "Admin",
//         email: "admin@gmail.com",
//         password: "1234",
//         modo: "administrador"
//     }),
//     new User({
//         name: "user",
//         email: "user@gmail.com",
//         password: "1234",
//     })
// ];

// palettes.forEach( p=> p.save());
// colors.forEach( c=> c.save());
// users.forEach( u=> u.save());